### PR TITLE
Create prep instructions

### PR DESCRIPTION
**Pull request by ZuliusRoolf**
Created a preparation file for us labrats to follow for setting up the workshop.
The c += 1 will be changed at later date to a count() function that will be introduced in the "instruction revision" branch.

The amount of wires in what color will need to be edited at later date

### CODE REVIEW

**Comment by adamzki99** [comment]
There should not be a need to "copy" code from a txt-file.

Better to create the file in a new directory of the repository

**Comment by ZuliusRoolf** [comment]
Added a new directory called prep, with a todo.txt (previously known as prep.txt), a file with the test code and a test.sh script copying the test code, apply it into main.py and runs the python test.
Also moved the "install_workshop_dependencies" script into the same directory as I deem it "prep worthy".

**Comment by andreas-bauer** [comment]
What is the purpose of the `prep/test.sh`?

**Comment by ZuliusRoolf** [comment]
it just does the "copy paste" part for you and runs the python test provided in "code4tests.txt"
Maybe a bit over-engineered...

**Review by andreas-bauer — CHANGES_REQUESTED** [review]
@ShiraZull please rename `code4tests.txt` to `check.py`. The wording tests implies unit tests and other types of tests.

Please delete `prep/test.sh` since it introduces additional complexity without providing additional value.

**Comment by ZuliusRoolf** [comment]
@andreas-bauer Just making sure, check.py will then be a copy of main.py but with additional test code, right?

**Comment by andreas-bauer** [comment]
@ShiraZull `check.py` is just your `code3tests.txt` file as a Python file. 
The purpose would be to run it to see if all sensors are working.

**Comment by adamzki99** [comment]
@ShiraZull What is the purpose of the todo.txt? Is that a personal note that has been accidentally added in the initial commit?

If it is documentation regarding how to perform the lab, add it in the README instead.

**Comment by ZuliusRoolf** [comment]
@adamzki99 Todo.txt are instructions on what needs to be prepared before opening the workshop. 
I wanted to have it in a separate file from README.md as Todo.txt only involves instructions to prepare the tasks, nothing else.

README includes how to install raspberry pie OS, a description, code. I don't want to get distracted with unnecessary information 30 minutes before participants will gather and take a seat.

You could see it as:
README will prepare the raspberry pies to be used for the workshop.
Todo will prepare the workshop itself right before participants gather.

**Pull request merged**
